// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContactInformation struct {
	Name                 string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MobileNo             string                        `protobuf:"bytes,2,opt,name=mobile_no,json=mobileNo,proto3" json:"mobile_no,omitempty"`
	OfficeNo             string                        `protobuf:"bytes,3,opt,name=office_no,json=officeNo,proto3" json:"office_no,omitempty"`
	Email                string                        `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Id                   int32                         `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	Address              []*ContactInformation_Address `protobuf:"bytes,5,rep,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ContactInformation) Reset()         { *m = ContactInformation{} }
func (m *ContactInformation) String() string { return proto.CompactTextString(m) }
func (*ContactInformation) ProtoMessage()    {}
func (*ContactInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *ContactInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactInformation.Unmarshal(m, b)
}
func (m *ContactInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactInformation.Marshal(b, m, deterministic)
}
func (m *ContactInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactInformation.Merge(m, src)
}
func (m *ContactInformation) XXX_Size() int {
	return xxx_messageInfo_ContactInformation.Size(m)
}
func (m *ContactInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactInformation.DiscardUnknown(m)
}

var xxx_messageInfo_ContactInformation proto.InternalMessageInfo

func (m *ContactInformation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContactInformation) GetMobileNo() string {
	if m != nil {
		return m.MobileNo
	}
	return ""
}

func (m *ContactInformation) GetOfficeNo() string {
	if m != nil {
		return m.OfficeNo
	}
	return ""
}

func (m *ContactInformation) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ContactInformation) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ContactInformation) GetAddress() []*ContactInformation_Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type ContactInformation_Address struct {
	Line_1               string   `protobuf:"bytes,1,opt,name=line_1,json=line1,proto3" json:"line_1,omitempty"`
	Line_2               string   `protobuf:"bytes,2,opt,name=line_2,json=line2,proto3" json:"line_2,omitempty"`
	Postcode             string   `protobuf:"bytes,3,opt,name=postcode,proto3" json:"postcode,omitempty"`
	Country              string   `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	City                 string   `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactInformation_Address) Reset()         { *m = ContactInformation_Address{} }
func (m *ContactInformation_Address) String() string { return proto.CompactTextString(m) }
func (*ContactInformation_Address) ProtoMessage()    {}
func (*ContactInformation_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0, 0}
}

func (m *ContactInformation_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactInformation_Address.Unmarshal(m, b)
}
func (m *ContactInformation_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactInformation_Address.Marshal(b, m, deterministic)
}
func (m *ContactInformation_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactInformation_Address.Merge(m, src)
}
func (m *ContactInformation_Address) XXX_Size() int {
	return xxx_messageInfo_ContactInformation_Address.Size(m)
}
func (m *ContactInformation_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactInformation_Address.DiscardUnknown(m)
}

var xxx_messageInfo_ContactInformation_Address proto.InternalMessageInfo

func (m *ContactInformation_Address) GetLine_1() string {
	if m != nil {
		return m.Line_1
	}
	return ""
}

func (m *ContactInformation_Address) GetLine_2() string {
	if m != nil {
		return m.Line_2
	}
	return ""
}

func (m *ContactInformation_Address) GetPostcode() string {
	if m != nil {
		return m.Postcode
	}
	return ""
}

func (m *ContactInformation_Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *ContactInformation_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

type ContactResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactResponse) Reset()         { *m = ContactResponse{} }
func (m *ContactResponse) String() string { return proto.CompactTextString(m) }
func (*ContactResponse) ProtoMessage()    {}
func (*ContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *ContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactResponse.Unmarshal(m, b)
}
func (m *ContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactResponse.Marshal(b, m, deterministic)
}
func (m *ContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactResponse.Merge(m, src)
}
func (m *ContactResponse) XXX_Size() int {
	return xxx_messageInfo_ContactResponse.Size(m)
}
func (m *ContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContactResponse proto.InternalMessageInfo

func (m *ContactResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ContactResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ContactSearch struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactSearch) Reset()         { *m = ContactSearch{} }
func (m *ContactSearch) String() string { return proto.CompactTextString(m) }
func (*ContactSearch) ProtoMessage()    {}
func (*ContactSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *ContactSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactSearch.Unmarshal(m, b)
}
func (m *ContactSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactSearch.Marshal(b, m, deterministic)
}
func (m *ContactSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactSearch.Merge(m, src)
}
func (m *ContactSearch) XXX_Size() int {
	return xxx_messageInfo_ContactSearch.Size(m)
}
func (m *ContactSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactSearch.DiscardUnknown(m)
}

var xxx_messageInfo_ContactSearch proto.InternalMessageInfo

func (m *ContactSearch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ContactInformation)(nil), "api.ContactInformation")
	proto.RegisterType((*ContactInformation_Address)(nil), "api.ContactInformation.Address")
	proto.RegisterType((*ContactResponse)(nil), "api.ContactResponse")
	proto.RegisterType((*ContactSearch)(nil), "api.ContactSearch")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x9b, 0xb4, 0x69, 0xda, 0x29, 0x7e, 0x30, 0x54, 0x5c, 0xe2, 0xc1, 0x12, 0x2f, 0x3d,
	0x15, 0x1b, 0x4f, 0x22, 0x08, 0xd2, 0x83, 0x78, 0xe9, 0x21, 0x3e, 0x40, 0xd9, 0x6e, 0xb6, 0xb8,
	0xd0, 0xec, 0x84, 0x64, 0x8b, 0xf4, 0xe8, 0x0b, 0xf8, 0x5a, 0xbe, 0x96, 0x24, 0xd9, 0x2d, 0x05,
	0xed, 0x6d, 0xfe, 0x1f, 0x09, 0xbf, 0x99, 0x04, 0x86, 0xbc, 0x50, 0xb3, 0xa2, 0x24, 0x43, 0xd8,
	0xe5, 0x85, 0x8a, 0x7f, 0x7c, 0xc0, 0x05, 0x69, 0xc3, 0x85, 0x79, 0xd3, 0x1b, 0x2a, 0x73, 0x6e,
	0x14, 0x69, 0x44, 0xe8, 0x69, 0x9e, 0x4b, 0xe6, 0x4d, 0xbc, 0xe9, 0x30, 0x6d, 0x66, 0xbc, 0x81,
	0x61, 0x4e, 0x6b, 0xb5, 0x95, 0x2b, 0x4d, 0xcc, 0x6f, 0x82, 0x41, 0x6b, 0x2c, 0xa9, 0x0e, 0x69,
	0xb3, 0x51, 0xa2, 0x09, 0xbb, 0x6d, 0xd8, 0x1a, 0x4b, 0xc2, 0x31, 0x04, 0x32, 0xe7, 0x6a, 0xcb,
	0x7a, 0x4d, 0xd0, 0x0a, 0x3c, 0x07, 0x5f, 0x65, 0xac, 0x3f, 0xf1, 0xa6, 0x41, 0xea, 0xab, 0x0c,
	0x1f, 0x21, 0xe4, 0x59, 0x56, 0xca, 0xaa, 0x62, 0xc1, 0xa4, 0x3b, 0x1d, 0x25, 0xb7, 0xb3, 0x1a,
	0xf6, 0x2f, 0xdd, 0xec, 0xa5, 0xad, 0xa5, 0xae, 0x1f, 0x7d, 0x79, 0x10, 0x5a, 0x13, 0xaf, 0xa0,
	0xbf, 0x55, 0x5a, 0xae, 0xe6, 0x16, 0x3e, 0xa8, 0xd5, 0xfc, 0x60, 0x27, 0x16, 0xbd, 0xb1, 0x13,
	0x8c, 0x60, 0x50, 0x50, 0x65, 0x04, 0x65, 0xd2, 0x61, 0x3b, 0x8d, 0x0c, 0x42, 0x41, 0x3b, 0x6d,
	0xca, 0xbd, 0x05, 0x77, 0xb2, 0x3e, 0x8f, 0x50, 0x66, 0xcf, 0x82, 0xf6, 0x3c, 0xf5, 0x1c, 0x3f,
	0xc1, 0x85, 0x45, 0x4d, 0x65, 0x55, 0x90, 0xae, 0xa4, 0xdd, 0xd0, 0x3b, 0x6c, 0xc8, 0x20, 0xac,
	0x76, 0x42, 0xd4, 0x1b, 0xd6, 0x10, 0x83, 0xd4, 0xc9, 0xf8, 0x0e, 0xce, 0xec, 0xc3, 0xef, 0x92,
	0x97, 0xe2, 0xe3, 0xbf, 0x0f, 0x90, 0x7c, 0x7b, 0x10, 0xda, 0x16, 0x2e, 0xe0, 0x72, 0x51, 0x4a,
	0x6e, 0xe4, 0x52, 0x7e, 0x3a, 0xef, 0xfa, 0xc4, 0xbd, 0xa2, 0xf1, 0x71, 0xe0, 0xe8, 0xe2, 0x0e,
	0x3e, 0xc3, 0xe8, 0x55, 0x1a, 0xeb, 0x57, 0x88, 0xc7, 0xb5, 0x96, 0x23, 0x3a, 0xf5, 0xce, 0xb8,
	0x73, 0xef, 0xad, 0xfb, 0xcd, 0x8f, 0xf4, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xb6, 0xb2, 0xfd,
	0x15, 0x55, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContactClient is the client API for Contact service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactClient interface {
	CreateNewContact(ctx context.Context, in *ContactInformation, opts ...grpc.CallOption) (*ContactResponse, error)
	GetContacts(ctx context.Context, in *ContactSearch, opts ...grpc.CallOption) (Contact_GetContactsClient, error)
}

type contactClient struct {
	cc *grpc.ClientConn
}

func NewContactClient(cc *grpc.ClientConn) ContactClient {
	return &contactClient{cc}
}

func (c *contactClient) CreateNewContact(ctx context.Context, in *ContactInformation, opts ...grpc.CallOption) (*ContactResponse, error) {
	out := new(ContactResponse)
	err := c.cc.Invoke(ctx, "/api.Contact/CreateNewContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactClient) GetContacts(ctx context.Context, in *ContactSearch, opts ...grpc.CallOption) (Contact_GetContactsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Contact_serviceDesc.Streams[0], "/api.Contact/GetContacts", opts...)
	if err != nil {
		return nil, err
	}
	x := &contactGetContactsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Contact_GetContactsClient interface {
	Recv() (*ContactInformation, error)
	grpc.ClientStream
}

type contactGetContactsClient struct {
	grpc.ClientStream
}

func (x *contactGetContactsClient) Recv() (*ContactInformation, error) {
	m := new(ContactInformation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ContactServer is the server API for Contact service.
type ContactServer interface {
	CreateNewContact(context.Context, *ContactInformation) (*ContactResponse, error)
	GetContacts(*ContactSearch, Contact_GetContactsServer) error
}

func RegisterContactServer(s *grpc.Server, srv ContactServer) {
	s.RegisterService(&_Contact_serviceDesc, srv)
}

func _Contact_CreateNewContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContactInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServer).CreateNewContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Contact/CreateNewContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServer).CreateNewContact(ctx, req.(*ContactInformation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contact_GetContacts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ContactSearch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContactServer).GetContacts(m, &contactGetContactsServer{stream})
}

type Contact_GetContactsServer interface {
	Send(*ContactInformation) error
	grpc.ServerStream
}

type contactGetContactsServer struct {
	grpc.ServerStream
}

func (x *contactGetContactsServer) Send(m *ContactInformation) error {
	return x.ServerStream.SendMsg(m)
}

var _Contact_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Contact",
	HandlerType: (*ContactServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewContact",
			Handler:    _Contact_CreateNewContact_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetContacts",
			Handler:       _Contact_GetContacts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
